import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Cosmo Crystals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback="Loading...">
      <Header options={false} />
      {children}
    </Suspense>
  );
}
